run:
  concurrency: 4
  timeout: 5m
  tests: false
linters:
  disable-all: true
  enable:
    - cyclop
    - bodyclose
    - containedctx
    - contextcheck
    - deadcode
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - gofmt
    - gomod
    - golint
    - importas
    - nilerr
  # Enable presets.
  # https://golangci-lint.run/usage/linters
  # Default: []
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  # Run only fast linters from enabled linters set (first run won't be fast)
  # Default: false
  fast: true